language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      brew update;
      brew install pcre;
      brew install source-highlight;
      brew install coreutils;
      brew install gdb;
    fi;

addons:
  apt:
    packages:
      - gdb
      - bison
      - flex
      - libncurses5-dev
      - libncursesw5-dev
      - libpcre3-dev
      - realpath
      - libsource-highlight-dev
      - libboost-regex-dev

before_script:
  - ulimit -c unlimited

script: ./configure && make dev

after_failure:
  - COREFILE=tests/text/core
  - if [ -f "$COREFILE" ]; then
      gdb -c "$COREFILE" wed -ex bt -batch;
    fi;

