language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
      - bison
      - flex
      - libncurses5-dev
      - libncursesw5-dev
      - libpcre3-dev
      - realpath
      - libsource-highlight-dev
      - libboost-regex-dev

script: make dev

