language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      brew update;
      brew install pcre;
      brew install source-highlight;
      brew install coreutils;
      brew install lua;
      luarocks install lpeg;
    fi;

addons:
  apt:
    packages:
      - bison
      - flex
      - libncurses5-dev
      - libncursesw5-dev
      - libpcre3-dev
      - realpath
      - libsource-highlight-dev
      - libboost-regex-dev
      - liblua5.1-0-dev
      - liblua5.1-lpeg2
      - lua5.1

script: ./configure --enable-gnu-source-highlight && make dev

