language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - bison
      - flex
      - libncurses5-dev
      - libncursesw5-dev
      - libpcre3-dev
      - realpath
      - libsource-highlight-dev
      - libboost-regex-dev

script: make dev

